### ISSUE TITLE
Frontend build fails if src/exercises/ directory is missing

### ISSUE THREAD

**Issue by Im-Arth1307** [JdeRobot/RoboticsAcademy#3046]
### **Description**
When running `npm run build`, the frontend build fails if the `src/exercises/` directory is missing. This is caused by a dynamic import in `src/exercise-index.js `(around line 70), which expects files to be present in that folder.
line:
``rendered_component = await import(`exercises/${component_path}`).then(...)``

While local development might work (e.g., when using dev servers or mounted volumes), production builds and CI/CD pipelines break, leading to confusion for new users and contributors.

I'm currently a GSoC 2025 applicant for this organization (awaiting results), and encountered this issue while trying to test UI changes and following the standard build process after cloning the repo.

### **Steps to Reproduce**

1. Clone the repository.

2. Navigate to react_frontend/ and run:
```
npm install
npm run build
```
3. Observe the build failure:
```
ERROR in ./src/exercise-index.js
Module not found: Error: Can't resolve 'exercises'
```

### **Why this matters**

- Build fails: Without the folder, `npm run build` doesn’t work.
- Inconsistent experience: Some local setups may work without a build, hiding the issue.

### **Suggested Fixes**

- Add a placeholder `src/exercises/` folder with a dummy file.
-  Improve `exercise-index.js` to handle missing files gracefully and warn instead of crashing.

**Comment by Zouziszzm** [comment]
I have fixed this issues, and also found out another issue  " Replace broken static import of `common.zip`" in `PlayPauseButton.js`. so have fixed that as well.

**Comment by javizqh** [comment]
Please make sure to read the [documentation](https://github.com/JdeRobot/RoboticsAcademy/blob/humble-devel/docs/InstructionsForDevelopers.md) on how to launch Robotics Academy first.

Can you please respond if after following those steps, either using docker run or our developer script, this issue is still happening to you.

**Comment by Im-Arth1307** [comment]
Yes, I’ve previously been able to launch Robotics Academy successfully using the provided instructions (including both the Docker-based setup and the developer script). The platform was working as expected.

That said, I encountered this issue while exploring UI-related changes and trying to build the frontend manually using` npm run build`. While this isn't part of the standard setup path, the issue could still affect contributors or CI/CD pipelines where the build step is required.

While the main workflows work fine, I thought it might be worth flagging this edge case.

**Comment by javizqh** [comment]
To develop the frontend we use the developer script, that thanks to the last changes updates in real time the changes without needing to relaunch the docker containers. We do not support local development because of our goal of being multiplatform and compatibility with other tools.

That said, does this happen when you try using `develop_academy.sh`?

**Comment by Zouziszzm** [comment]
ah will do check that  its my bad that i didn't read  them. if the issues is not already fixed will fix it , @javizqh  thanks for responding.

**Comment by Im-Arth1307** [comment]
@javizqh No, this issue doesn't arise while using `develop_academy.sh`, and the live-reloading experience worked well. The issue only came up when I tried a manual `npm run build` after cloning the repo to test a custom change. I thought it might still be worth flagging.

**Comment by javizqh** [comment]
As said before we do not support local development methods outside of the ones stated in the documentation and will not change in the foreseeable future.

**Comment by Im-Arth1307** [comment]
Ok, thank you for the confirmation !
